### PR TITLE
Cover-Images added to the format list

### PR DESCRIPTION
**Pull request by dan-and**
Based on 3rgo's code to add cover images, I moved over his config to the format list and modified the URL to download the cover image instead of just the thumbnail. 

You are able to download the covers of the books now as default.

### CODE REVIEW

**Comment by ozzieperez** [comment]
@dan-and / @3rgo  this is great, thanks! 
One small thing.. looks like you're using spaces for indentation and it throws an error with python3:
screen shot 2017-07-18 at 1 53 13 pm

screen shot 2017-07-18 at 1 33 51 pm

Could you update the indentations to use tabs instead? Otherwise, works well. 👍

**Comment by 3rgo** [comment]
Yeah i can do that, but I'm still working on downloading the higher
resolution image from the product page, as well as the description. I hope
to have this done by this weekend

**Comment by ozzieperez** [comment]
@3rgo, thanks. sounds good. 👌

**Comment by dan-and** [comment]
Will do that tonight. Sorry for that.

**Comment by dan-and** [comment]
@3rgo the larger images are already in my patch. Or did I misunderstood you?

**Comment by 3rgo** [comment]
Sorry, I'm still wrapping up my mind on Github workflows. Since I've forked ozzie's repo, I didn't know you could merge my changes. I'll have to switch origins to fetch them.
It'll get me the larger images, but I'm still working on the description, my XPath is still rudimentary

**Pull request merged**
