### PR TITLE
Video download features

### PR DESCRIPTION
**Pull request by dan-and**
Hey ozzie, 

I am not very pleased with this copy&paste solution, but I just need to download video files as well. Have a look at the chances and decide on your own. 

it's possible to select the format: video to download the videos 
Additionally you can force "ebook only" or "video only" regardless of the selections in the format options.

### CODE REVIEW

**Comment by ozzieperez** [comment]
This is really cool @dan-and. Let me take a look at it. I'm also considering rolling the "include-code" flag into the comma-delimited list of files to download (pdf,epub,jpg,etc..) instead of it being a flag on it's own. So the "-f" option would be changed to mean "--files" instead of ""--formats". 
Thanks again.

**Comment by dan-and** [comment]
That is a good idea. I would align this patch accordingly.

**Comment by dan-and** [comment]
Added your request to both the master and the video-dl branch.

**Comment by ozzieperez** [comment]
This is great, @dan-and. I had planned on doing the update for the --include-code, but thanks for beating me to it! ; D I'll take a look later today and go over it. Looks good though. 👍

**Pull request merged**
