### PR TITLE
bug fixing when download book name with apostrof.

### PR DESCRIPTION
**Pull request by irzan2010**
There is some kind of bug that caused program can't download e-Book with positron in its name. For example "ABC's example of blah blah bla"

### CODE REVIEW

**Comment by ozzieperez** [comment]
Hey @irzan2010 , thanks for notifying on the bug. It looks like the file must've gotten mangled when doing the pull request. Please take a look at it and only submit the lines that were changed. I've been busy, but I also have pending to integrate the other pull requests. I'll incorporate this fix when I do those.
Thanks again

**Comment by irzan2010** [comment]
I am sorry, it's my mistake. I am new to GitHub.
So how I fix it? Should I do another pull request and cancel this one?

**Comment by ozzieperez** [comment]
@irzan2010, download SourceTree. It allows you to easily see the changes that you're going to commit and omit any changes that you didn't mean to commit. 

Image of SourceTree

On the right panel where you see the code changes, you can click the elipses (the 3 dots ...) in code you didn't mean to change and chose to "Discard Hunk" and it will clean up the commit. You can also discard specific lines by highlighting them, and the option to "Discard Lines" will appear.

Let me know if you need any more help, ok.

**Comment by irzan2010** [comment]
Hi, I've downloaded SourceTree, but I can not find "Discard Hunk" menu. The only menu that I see is "Reverse Hunk".

image

**Comment by ozzieperez** [comment]
@irzan2010 , let's revert your commit on the 'big-fix' branch, add your fix, and then do a new commit.

Here's how:

**Revert the commit**
- save a copy of your code somewhere on your computer so that you have the change that you made before we revert the code
- right-click on the commit below (f959865)
- select "Reset bug-fix to this commit"

Now, add your fix to the code. 

On the left panel of SourceTree, click on "Working Copy" to see the changes that are going to be committed. Make sure it's only the changes that you made. This is where you'll see "Discard Hunk" as an option.

Once you verified that your code is ready for a commit, commit the change the way you usually do it, or you can do it with SourceTree by selecting the file in the "Unstaged files" panel and dragging it up to the "Staged files" panel. Then at the bottom of the UI write a commit message and click the "Commit" button. 

Let me know if this made any sense. ☺️

**Comment by irzan2010** [comment]
Hi, sorry for late reply. 
I have committed my code to my repository. What to do now? Should I make a pull request again?

**Comment by ozzieperez** [comment]
@irzan2010, your last PR was perfect. I merged it into the code base. Sorry for the later reply. Thanks again! 👍

**Comment by irzan2010** [comment]
You're welcome. I am glad to help.

**Pull request merged**
